### ISSUE TITLE
Power operator missing from README

### ISSUE THREAD

**Issue by MichaelClerx** [martinjrobins/diffeq-js#1]
pow(5, 2) outputs 25, but isn't mentioned in the README

**Comment by martinjrobins** [comment]
thanks @MichaelClerx! FYI, I've now open-sourced the backend compiler [here](https://github.com/martinjrobins/diffsl) and plan to put documentation there going forward (when I have time!)

**Comment by martinjrobins** [comment]
diffsl docs now here: https://martinjrobins.github.io/diffsl/
