### ISSUE TITLE
Compatibility with Vite (Vue/React)

### ISSUE THREAD

**Issue by acosta-leandro** [martinjrobins/diffeq-js#2]
#### Problem Description
When the package is run on a browser in a frontend handled by Vite, the outputs are empty.
[Example](https://github.com/acosta-leandro/test-diffeq-js/blob/main/src/App.vue)

#### Observed Behavior
- **Webpack versions earlier than 5**: Works well, as they still include Node.js built-ins.
- **Webpack 5 or higher**: Breaks, as they no longer include Node.js built-ins.
- **Vite**: Always breaks.

#### Steps to Reproduce
1. Minimal repo that reproduce the problem [Repo](https://github.com/acosta-leandro/test-diffeq-js/)
2. npm install
3. npm run dev
4. open in browser and check console

#### Environment
- **Diffeq-js Version**: 0.1.4
- **Build Tool**: Vite / Webpack 5+
- **Node Version**: 20.13.1
- **Operating System**: Apple M1 - Sonoma 14.4.1
- **Browsers Tested**: Firefox (127.0.2), Arc (1.49.1), Chrome (arm 126.0.6478.127)

Thank you.
![image](https://github.com/user-attachments/assets/afb17654-0410-4352-a6ae-f3151c302cd7)
![image](https://github.com/user-attachments/assets/f184077e-1de9-4415-b9ec-88bc135a8153)

**Comment by martinjrobins** [comment]
thanks @acosta-leandro for reporting this. I'll have a look and get back to you

**Comment by martinjrobins** [comment]
I have published a new version of diffeq-js which I think should fix your problem, can you try version `0.1.5-alpha.0` and see if that works for you

**Comment by acosta-leandro** [comment]
It works and solves the related issue.
